spring:
  data:
    mongodb:
      # URI will be dynamically set by TestContainers
      auto-index-creation: false # Disable to speed up tests
  task:
    scheduling:
      enabled: false
  test:
    mockmvc:
      print: default
  # Disable caching for tests
  cache:
    type: none
  # Disable Redis auto-configuration for tests
  #autoconfigure:
  #  exclude:
  #    - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  #    - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  # Prevent Redis connection issues during tests

  #redis:
  #  repositories:
  #    enabled: false

  main:
    allow-bean-definition-overriding: true
  mail:
    host: localhost
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

jwt:
  secure: false
  same-site: Lax
  access-token-expiration-seconds: 60 # Short 1-minute tokens for tests
  refresh-token-expiration-seconds: 300 # 5 minutes


# Test-specific logging
logging:
  level:
    dev.ehutson.template: DEBUG
    org.springframework.test: DEBUG
    org.springframework.security: DEBUG

app:
  mail:
    from: "foo@bar.com"
    baseUrl: "http://localhost:8080"
    enabled: true