spring:
  data:
    mongodb:
      auto-index-creation: true
      host: ${PROD_MONGO_HOST:localhost}
      port: ${PROD_MONGO_PORT:27017}
      database: ${PROD_MONGO_DATABASE:template}
      username: ${PROD_MONGO_USERNAME:template_app_user}
      password: ${PROD_MONGO_PASSWORD:template_app_password}
    redis:
      host: ${PROD_REDIS_HOST:localhost}
      port: ${PROD_REDIS_PORT:6379}
      username: ${PROD_REDIS_USERNAME:template_redis_user}
      password: ${PROD_REDIS_PASSWORD:template_redis_password}
  kafka:
    bootstrap-servers: ${PROD_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    security:
      protocol: SSL
    consumer:
      group-id: template-group
  graphql:
    cors:
      allowed-origins: ${PROD_GRAPHQL_CORS_ALLOWED_ORIGINS:http://localhost:3000}
  docker:
    compose:
      enabled: false

jwt:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
  http-only: true
  same-site: Strict
  secure: true
  access-token-expiration-seconds: 3600  # 1 hour in seconds
  refresh-token-expiration-seconds: 604800  # 7 days in seconds

logging:
  level:
    root: WARN
    dev.ehutson.template: INFO
    org.springframework: WARN

management:
  endpoint:
    health:
      show-details: never

mail:
  enabled: true
  from: "foo@bar.com"
  base-url: "https://my_server_url.com"