spring:
  data:
    mongodb:
      auto-index-creation: false
      host: localhost
      port: 27017
      database: template2
      username: template_app_user
      password: template_app_password
    redis:
      host: localhost
      port: 6379
  task:
    scheduling:
      enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: template-group

  graphql:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "Content-Type, Authorization"
      exposed-headers: X-Auth-Token

  mail:
    host: localhost
    port: 25
    username:
    password:

  messages:
    cache-duration: PT1S  # 1 second, see the ISO 8601 standard

  thymeleaf:
    cache: false

jwt:
  secure: false
  same-site: Lax
  access-token-expiration-seconds: 3600  # 1 hour in seconds
  refresh-token-expiration-seconds: 604800  # 7 days in seconds


logging:
  level:
    dev.ehutson.template: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO

mail:
  enabled: true
  from: foo@bar.com
  base-url: http://localhost:8080 # The base URL of the application, used for creating links in emails
