spring:
  profiles:
    default: dev

  data:
    mongodb:
      auto-index-creation: false
      host: localhost
      port: 27017
      database: template2
      username: template_app_user
      password: template_app_password

  graphql:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "Content-Type, Authorization"
      exposed-headers: X-Auth-Token
      max-age: 3600

  docker:
    compose:
      enabled: false

server:
  port: 8097

mongock:
  migration-scan-package: dev.ehutson.template.migration
  enabled: true
  runner-type: initializingbean
  transaction-enabled: false
  track-ignored: true

jwt:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem



