name: template
services:
  sonar:
    container_name: sonarqube
    image: sonarqube:lts-community
    # Forced authentication redirect for UI is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete SONAR_FORCEAUTHENTICATION variable or set SONAR_FORCEAUTHENTICATION=true
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - "9001:9001"
      - "9000:9000"